### ISSUE TITLE
Roadmap to V1

### ISSUE THREAD

**Issue by jdormit** [pterotype-project/activitypub-php#5]
cc @squeevee

This issue is to track the stuff that still needs to get done before the library is ready for use. There are a few categories:

## Core ActivityPub implementation
Every activity type that requires special handling needs a `Handler` class in `ActivityPub\Activities`, plus we'll need a handler to persist all incoming activities and a handler to deliver activities to other server (S2S federation). This will also involve implementing some plumbing elsewhere in the codebase (e.g., checking for blocks when receiving activities)
- [X] ActivityValidator
- [X] NonActivityHandler (wraps non-activities in Creates)
- [X] CreateHandler
- [ ] UpdateHandler
- [ ] DeleteHandler
- [ ] FollowHandler
- [ ] AcceptHandler
- [ ] RejectHandler
- [ ] AddHandler
- [ ] RemoveHandler
- [ ] LikeHandler
- [ ] BlockHandler
- [ ] AnnounceHandler
- [ ] UndoHandler
- [ ] ActivityPersister
- [ ] ActivityDeliverer

## Library API
Callers will probably want do ActivityPub stuff without having manually construct a `Request` and pass it to the request handler, so we should expose some API methods in `ActivityPub.php` - `createActor`, `postActivity`, etc.
- [ ] Implement the public API

## WebFinger
As discussed in #2, we need to implement an optional WebFinger API to make it easy for callers to participate in WebFinger discovery
- [ ] Implement WebFinger

## Caching
The current implementation could thrash the database pretty hard if a bunch of requests come in for the same id in a short amount of time, which is pretty common due to AP's federation model. We should put in a pluggable caching layer over `ObjectsService::query` that caches queries for particular ids, and invalidates the cache whenever the object referenced by that id changes (via `replace`, `update`, etc.). This will be a [PSR-16](https://www.php-fig.org/psr/psr-16/)-compatible `Cache` object that gets passed into `ObjectsService`. The cache will default to a [PHP Cache](http://www.php-cache.com/en/latest/) filesystem cache, but we'll expose an option in the config that lets callers pass in any PSR16-compliant cache implementation, allowing them to use Memcached, Redis, etc.

- [ ] Implement the caching layer

## Integration (end-to-end) testing
Once the rest of the API is complete, I want to write some end-to-end tests that pass in various `Requests` and make sure that the database state is what we would expect, that the `Response` that gets returned is correct, etc.

- [ ] Write integration tests

## Next steps
Once the above items are done and tested, I would consider the library ready for preliminary use. Longer term, I also want to think about implementing a builder-pattern API for constructing AP activities and objects to make things a little more type-safe and elegant. I don't a strict type system though, as that would make it more difficult to extend ActivityPub in client applications, so these builders would probably still return arrays that get passed into the existing library functions.

Any thoughts or suggestions are welcome!

**Comment by Cambridgeport90** [comment]
This looks really sweet. I'm keeping an eye on this one.

**Comment by poVoq** [comment]
Wow, almost there.
Probably worth trying to get other php projects on board. I made a post here:
https://github.com/nextcloud/social/issues/501

**Comment by jdormit** [comment]
@poVoq awesome, thanks! I'm working through some thoughts right now about how the library handles JSON-LD (which currently is, "it doesn't"), so that will probably create some additional work before I can move on to the public API.

**Comment by Cambridgeport90** [comment]
Sounds interesting. Keeping a hazel eye out; let me know if you need a helping hand with testing, because I have plenty of resources.
